import React from 'react';
export const sharingDetails = () => <div>sharing distinct</div>;
export const sharing_detail_0 = (p:any)=> <div>sharing 0 grant</div>;
export const sharing_detail_1 = (p:any)=> <div>sharing 1 emergency 48h</div>;
export const sharing_detail_2 = (p:any)=> <div>sharing 2 QR</div>;
export const sharing_detail_3 = (p:any)=> <div>sharing 3 read until</div>;
export const sharing_detail_4 = (p:any)=> <div>sharing 4 grant</div>;
export const sharing_detail_5 = (p:any)=> <div>sharing 5 emergency 48h</div>;
export const sharing_detail_6 = (p:any)=> <div>sharing 6 QR</div>;
export const sharing_detail_7 = (p:any)=> <div>sharing 7 read until</div>;
export const sharing_detail_8 = (p:any)=> <div>sharing 8 grant</div>;
export const sharing_detail_9 = (p:any)=> <div>sharing 9 emergency 48h</div>;
export const sharing_detail_10 = (p:any)=> <div>sharing 10 QR</div>;
export const sharing_detail_11 = (p:any)=> <div>sharing 11 read until</div>;
export const sharing_detail_12 = (p:any)=> <div>sharing 12 grant</div>;
export const sharing_detail_13 = (p:any)=> <div>sharing 13 emergency 48h</div>;
export const sharing_detail_14 = (p:any)=> <div>sharing 14 QR</div>;
export const sharing_detail_15 = (p:any)=> <div>sharing 15 read until</div>;
export const sharing_detail_16 = (p:any)=> <div>sharing 16 grant</div>;
export const sharing_detail_17 = (p:any)=> <div>sharing 17 emergency 48h</div>;
export const sharing_detail_18 = (p:any)=> <div>sharing 18 QR</div>;
export const sharing_detail_19 = (p:any)=> <div>sharing 19 read until</div>;