import React from 'react';
export const cryptoDetails = () => <div>crypto distinct</div>;
export const crypto_detail_0 = (p:any)=> <div>crypto 0 wallet</div>;
export const crypto_detail_1 = (p:any)=> <div>crypto 1 seed phrase</div>;
export const crypto_detail_2 = (p:any)=> <div>crypto 2 NFT</div>;
export const crypto_detail_3 = (p:any)=> <div>crypto 3 domain</div>;
export const crypto_detail_4 = (p:any)=> <div>crypto 4 wallet</div>;
export const crypto_detail_5 = (p:any)=> <div>crypto 5 seed phrase</div>;
export const crypto_detail_6 = (p:any)=> <div>crypto 6 NFT</div>;
export const crypto_detail_7 = (p:any)=> <div>crypto 7 domain</div>;
export const crypto_detail_8 = (p:any)=> <div>crypto 8 wallet</div>;
export const crypto_detail_9 = (p:any)=> <div>crypto 9 seed phrase</div>;
export const crypto_detail_10 = (p:any)=> <div>crypto 10 NFT</div>;
export const crypto_detail_11 = (p:any)=> <div>crypto 11 domain</div>;
export const crypto_detail_12 = (p:any)=> <div>crypto 12 wallet</div>;
export const crypto_detail_13 = (p:any)=> <div>crypto 13 seed phrase</div>;
export const crypto_detail_14 = (p:any)=> <div>crypto 14 NFT</div>;
export const crypto_detail_15 = (p:any)=> <div>crypto 15 domain</div>;
export const crypto_detail_16 = (p:any)=> <div>crypto 16 wallet</div>;
export const crypto_detail_17 = (p:any)=> <div>crypto 17 seed phrase</div>;
export const crypto_detail_18 = (p:any)=> <div>crypto 18 NFT</div>;
export const crypto_detail_19 = (p:any)=> <div>crypto 19 domain</div>;