import React from 'react';
export const discoveryDetails = () => <div>discovery distinct</div>;
export const discovery_detail_0 = (p:any)=> <div>discovery 0 Gmail scan</div>;
export const discovery_detail_1 = (p:any)=> <div>discovery 1 OAuth</div>;
export const discovery_detail_2 = (p:any)=> <div>discovery 2 inventory</div>;
export const discovery_detail_3 = (p:any)=> <div>discovery 3 HaveIBeenPwned</div>;
export const discovery_detail_4 = (p:any)=> <div>discovery 4 Gmail scan</div>;
export const discovery_detail_5 = (p:any)=> <div>discovery 5 OAuth</div>;
export const discovery_detail_6 = (p:any)=> <div>discovery 6 inventory</div>;
export const discovery_detail_7 = (p:any)=> <div>discovery 7 HaveIBeenPwned</div>;
export const discovery_detail_8 = (p:any)=> <div>discovery 8 Gmail scan</div>;
export const discovery_detail_9 = (p:any)=> <div>discovery 9 OAuth</div>;
export const discovery_detail_10 = (p:any)=> <div>discovery 10 inventory</div>;
export const discovery_detail_11 = (p:any)=> <div>discovery 11 HaveIBeenPwned</div>;
export const discovery_detail_12 = (p:any)=> <div>discovery 12 Gmail scan</div>;
export const discovery_detail_13 = (p:any)=> <div>discovery 13 OAuth</div>;
export const discovery_detail_14 = (p:any)=> <div>discovery 14 inventory</div>;
export const discovery_detail_15 = (p:any)=> <div>discovery 15 HaveIBeenPwned</div>;
export const discovery_detail_16 = (p:any)=> <div>discovery 16 Gmail scan</div>;
export const discovery_detail_17 = (p:any)=> <div>discovery 17 OAuth</div>;
export const discovery_detail_18 = (p:any)=> <div>discovery 18 inventory</div>;
export const discovery_detail_19 = (p:any)=> <div>discovery 19 HaveIBeenPwned</div>;